### ISSUE TITLE
Compatibility with Windows

### ISSUE THREAD

**Issue by GillesOrban** [avigan/pyZELDA#29]
Hi,
trying to use pyZelda on a windows machine, we got some trouble with the 'pathlib' module (creating a 'WindowsPath' object) and 'ConfigParser'.

The fix was in the 'Sensor' class (line 105) to replace:
>> config.read(configfile)
by
>> config.read(configfile.as_posix())

should be compatible with linux.

cheers,
Gilles

**Comment by avigan** [comment]
Implemented in d53a72d. Closing ticket.
