### ISSUE TITLE
Possibility to have multiple clear pupil images

### ISSUE THREAD

**Issue by avigan** [avigan/pyZELDA#5]
Currently the code assumes that there is only a single clear pupil image for one or multiple ZELDA pupil images, but for some sequences, there can be one clear pupil image for each ZELDA pupil image. Supporting multiple clear pupil images needs to adapt the following methods:
- [x] read_files() and read_files_sequence() (or their merged version, see #3)
- [x] analyze()

**Comment by astromam** [comment]
Currently the code assumes data processing at a single wavelength, thus preventing the analysis of zelda images taken with an IFS. Introduce the option to work with a wavelength vector to work with image cube at different wavelengths.

**Comment by avigan** [comment]
Done.
